### ISSUE TITLE
grub4dos-0.4.6a-2015-07-09.7z menu help text not cleared

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#66]
3rd, 4th and 5th line of menu help text is not cleared when use cursor keys to move down menu.
Only the first and 2nd line is updated.
![image](https://cloud.githubusercontent.com/assets/1469350/8615918/e517fbd8-26ee-11e5-86f8-a9167d94de79.png)

**Comment by yaya2007** [comment]
Is the "/_ISO/MAINMENU/Aceonis......." does not change?
Please let us know the menu content

**Comment by steve6375** [comment]
It is just
title ssss \n yyyyy

single line

Actually, 1st and 2nd line work, but 3rd, 4th line do not and 5th line is not cleared.
e.g.
title xxxx\n111\n222\n333\n4444
boot
![image](https://cloud.githubusercontent.com/assets/1469350/8617778/3159833a-26ff-11e5-8841-3303c9c7481c.png)

**Comment by steve6375** [comment]
Also, help text is on extreme left.
I use menusetting to set menu position.
![image](https://cloud.githubusercontent.com/assets/1469350/8617829/a14b0f10-26ff-11e5-983a-7175c143df0f.png)

This is how it should look (previous version of grldr).
![image](https://cloud.githubusercontent.com/assets/1469350/8617855/d97fffc6-26ff-11e5-9af2-0fe677e352a5.png)

**Comment by steve6375** [comment]
Simple case

menu.lst
=======

password fred

title test\n1\n2\n3\n4\n5
boot

![image](https://cloud.githubusercontent.com/assets/1469350/8618055/2bc68cd0-2702-11e5-9326-04f98d0b5608.png)

**Comment by steve6375** [comment]
setmenu does move help text to right:

graphicsmode -1 800 600
setmenu --box x=8 y=2 w=0 h=20 l=4 --help=8=23
password fred
title test\n1\n2\n3\n4\n5
reboot
![image](https://cloud.githubusercontent.com/assets/1469350/8618154/57f7e726-2703-11e5-950a-309221c3546e.png)

But, if I use only 'menusetting'  then help text is on extreme left of screen.

**Comment by yaya2007** [comment]
Now only allows the user to use 2 lines to help.
I don't know, often use more than 2 lines to help the situation? Generally use a few lines?

**Comment by steve6375** [comment]
Should be compatible with old version. Some languages (e.g. German) use many and long words so 4 lines are needed.
Old version was 4 lines of help  with 5th line for message (e.g. Press 'p' to gain privileged control'.
Please keep it compatible.

**Comment by steve6375** [comment]
Here is test case for menusetting

graphicsmode -1 800 600
#setmenu --box x=8 y=2 w=0 h=20 l=4 --help=8=23
#/%grub%/menusetting.gz   %wdspace% %lnspace% %bdwidth% %tophelp% %noitems% %topstart% %menuw% %rstart%
/_ISO/e2b/grub/menusetting.gz   n n 1 23 20 2 85 8
password fred

title test\n1\n2\n3\n4\n5
reboot

![image](https://cloud.githubusercontent.com/assets/1469350/8618416/fb935daa-2705-11e5-97a0-aeb160faa768.png)

Value for menu_border.menu_help_x  should be set same as x-1 if not defined.

**Comment by steve6375** [comment]
P.S. Small typo in line 164 of stage2.c
grub_strcpy (buff + i,"Press ENTER or \'b\' to boot.\n"
should have space before Press
grub_strcpy (buff + i," Press ENTER or \'b\' to boot.\n"

**Comment by steve6375** [comment]
Example using 3 lines of help text in Easy2Boot
![image](https://cloud.githubusercontent.com/assets/1469350/8618662/280133d8-2708-11e5-813d-20a4fa6a4197.png)

**Comment by steve6375** [comment]
lines 139-143 missing so does not clear help text?
https://github.com/chenall/grub4dos/commit/5c469149afba623452bc2b01ed720d503df1b669#diff-81be4a1d76dd8eef0ae0ed522d4989c1

**Comment by yaya2007** [comment]
Has been updated

**Comment by steve6375** [comment]
Still many problems - not compatible + bugs

*menu.lst*
graphicsmode -1 800 600
#/%grub%/menusetting.gz %wdspace% %lnspace% %bdwidth% %tophelp% %noitems% %topstart% %menuw% %rstart%
/_ISO/e2b/grub/menusetting.gz n n 1 23 5 17 60 8
password fred

title test1A\nA123456789\nA123456789\nA123456789\nA123456789\nA123456789
reboot
title test2B\nB123456789\nB123456789\nB123456789\nB123456789\nB123456789
reboot
title test3C\nC123456789\nC123456789\nC123456789\nC123456789\nC123456789
reboot
title test4D\nD123456789\nD123456789\nD123456789\nD123456789\nD123456789
reboot
title test5E\nE123456789\nE123456789\nE123456789\nE123456789\nE123456789
reboot
title test6F\nF123456789\nF123456789\nF123456789\nF123456789\nF123456789
reboot
title test7G\nG123456789\nG123456789\nG123456789\nG123456789\nG123456789
reboot
title continue\n
set grub=_ISO/e2b/grub
cat /%grub%/menu.lst > (md)0xa100+0x50 && configfile (md)0xa100+0x50

old 0.4.5c and 0.4.6a compatible..
![image](https://cloud.githubusercontent.com/assets/1469350/8636918/6b022bb4-2871-11e5-8201-8e4f8a545fff.png)
![image](https://cloud.githubusercontent.com/assets/1469350/8636919/9f487388-2871-11e5-9497-77f81249d73a.png)
New 0.4.6a NOT COMPATIBLE
![image](https://cloud.githubusercontent.com/assets/1469350/8636936/475bc570-2872-11e5-81f6-4a12f4e03bf8.png)

1. Last 2 lines of menu not cleared when new menu page displayed (cursor down)
2. Menu help text in wrong position under menu (x-1 y+1 needed)
3. grub4dos help text should be suppressed if \n used in title
   + it should be on same xy position as menu help text with max of 4 lines. 
4. Only 4 lines of menu help text allowed (not 5 lines)
5. No menu index number displayed at top of menu

If add a color command, more problems:
color blue/red yellow/light-gray cyan/black magenta/cyan red/blue
![image](https://cloud.githubusercontent.com/assets/1469350/8636964/0d3e1878-2874-11e5-8ccc-f65ac4c3a074.png)
Should be
![image](https://cloud.githubusercontent.com/assets/1469350/8636966/2962d958-2874-11e5-8757-2d0a404cd1b3.png)

6. Menu text not cleared when page-down (see 'test3Cue' line)
7. Color of menu help text not set to cyan/black

Why have you added new NOTES??? This is not compatible with previous versions? Please can you remove NOTES feature and make consistent with previous versions? NOTES and Menu help text should occupy same 4 lines.

Please make new version compatible - it is very important.

**Comment by yaya2007** [comment]
Mainland can not download

**Comment by steve6375** [comment]
http://www.rmprepusb.com/tutorials/grub4dos/fonts-and-graphics/Fonts800.zip

**Comment by steve6375** [comment]
Complete USB drive test
https://onedrive.live.com/redir?resid=8A0F146CC7416BA9!1667&authkey=!AOm6OeG2FNibGgc&ithint=file%2c7z
![image](https://cloud.githubusercontent.com/assets/1469350/8637630/19c566fe-2893-11e5-8eea-674afc1bb0f1.png)

P.S. When chainloading, seems to be a [Hit Q to quit, any other key to continue] paging prompt with new grldr?

**Comment by steve6375** [comment]
0.4.6a 2015-07-14 still have few problems.

1. Menu help text needs moving 2 characters to left

2. 'Use the ^ and v keys...' text is partially cleared when highlighted menu is changed.
![image](https://cloud.githubusercontent.com/assets/1469350/8672714/e86ae7b8-2a28-11e5-882a-d5afcf97c3d2.png)

3. Get a '[Hit Q to quit... message when select the grub old menu (must move cursor up menu first)
 - i.e. press cursor down until get to 'grub old' and run it.
![image](https://cloud.githubusercontent.com/assets/1469350/8672782/6e95f954-2a29-11e5-9bc2-0f85e4dd9039.png)
4. In old version, the NOTES text is in same place as menu help text (not at bottom of screen). if \n in title then NOTES text is supressed
![image](https://cloud.githubusercontent.com/assets/1469350/8672860/08cae0ca-2a2a-11e5-8f05-4b676bf8909d.png)

5. If setmenu --help-off is used (normal Easy2Boot USB drive), then the text that is written at the bottom of the display is cleared.
setmenu --help-off
![image](https://cloud.githubusercontent.com/assets/1469350/8672958/cf64a93c-2a2a-11e5-8631-d92a7480e841.png)
normal
![image](https://cloud.githubusercontent.com/assets/1469350/8672993/038334ea-2a2b-11e5-9c70-02286d4c3abe.png)

**Comment by steve6375** [comment]
P.S.
setmenu --box x=7 y=3 w=30 h=10
>> error while parsing number
setmenu --box x=7 y=3 w=3 h=10
>> OK

**Comment by steve6375** [comment]
color --notes=0x2
changes menu help text to green  - it should change the NOTES text not menu help text
color --helptext=0xf
changes notes text and help text to white ????

**Comment by steve6375** [comment]
How to set position of menu help text and NOTES text??
Not in help setmenu ??

**Comment by steve6375** [comment]
If default menu timeout set, e.g. 
timeout 5
there is no timeout message countdown displayed??

**Comment by yaya2007** [comment]
"1.Menu help text needs moving 2 characters to left"
--notes=[x]=[y]=[line]

"2.'Use the ^ and v keys...' text is partially cleared when highlighted menu is changed"
I don't have a repeat error here. Please try the new version.

"3.Get a '[Hit Q to quit... message when select the 'grub old' menu (must move cursor down menu first)"
Do not understand, please tell me a little more, how to reproduce?

"4.In old version, the NOTES text is in same place as menu help text (not at bottom of screen). if \n in title then NOTES text is supressed."
.Has been amended. Default to the old version. Can also be flexible settings.

"5.If setmenu --help-off is used (normal Easy2Boot USB drive), then the text that is written at the bottom of the display is cleared"
Has been amended.

"setmenu --box x=7 y=3 w=30 h=10
 gives 'error while parsing number'
 setmenu --box x=7 y=3 w=0 h=10
 OK"
There is no space between X"w="  and "30"

".color --notes=0x2
 changes menu help text to green - it should change the NOTES text not menu help text
 color --helptext=0xf
 changes notes text AND help text to white ????"
colot is 0xrrggbb.24 color.

"How to set x,y position of menu help text and NOTES text??
 Not in help setmenu ??
 is setmenu --help=x=y for NOTES or menu help text? It seems to be for NOTES not help??
grub4dos hangs if setmenu --help=x=y is in middle of menu!"
Has been amended.

"If default menu timeout set, e.g. 
 timeout 5
 there is no timeout message countdown displayed??"
Do not understand, please tell me a little more, how to reproduce?

**Comment by yaya2007** [comment]
1.支持每像素16位彩色模式（64K 5:6:5）。
2.支持 jpg（jpeg，jpe）图像格式。
3.在 vbe 模式，使用 echo -rrggbb 可以显示 216 种彩色样本。
4.使用 echo -v 可以显示版本、内存信息。
5.color 函数增加参数：  notes=[color]  菜单项注释颜色；
6.增加 setmenu 函数，增强图形菜单编辑功能。参数：
  --ver-on --ver-off 版本信息打开/关闭。默认打开；
  --help-on --help-off 菜单帮助信息打开/关闭。默认打开。应当位于菜单项标题的参数之前；
  --lang=en --lang=zh 菜单帮助信息中英文切换。默认英文；
  --auto-num 打开菜单自动编号；
  --line-spacing=[s] --font-spacing=[s] 设置字符间距/行间距。单位：像素。默认0。应当位于下面的参数之前；
  --string=[x]=[y]=[color]=["string“] 字符串位置、颜色与内容，可用于标题，说明等。单位：列，行，24位色彩；
    注：如果省略颜色，位于菜单框以上按标题颜色，位于菜单框以下按帮助颜色；
          字符串头尾要加英文双引号；
          列数=图像水平像素/(字符宽+字符间距）   字符宽=8；
          行数=图像垂直像素/(字符高+行间距)      字符高=10；
  --notes=[x]=[y]=[line] 菜单项标题注释位置、最大行数。单位：列，行；
  --help=[x]=[y] 菜单帮助位置。单位：列，行；
  --box x=[x] y=[y] w=[w] h=[h] l=[l] 菜单项标题起始列，起始行，每行最大字符数，最大菜单项数，菜单框线条宽度（像素）；
    注：w=0 表示水平居中。此时 w 应当在 x 之后；
       l=0 表示不显示菜单框；
  --u 恢复菜单原始状态。

**Comment by steve6375** [comment]
Please test with
https://onedrive.live.com/redir?resid=8A0F146CC7416BA9!1667&authkey=!AOm6OeG2FNibGgc&ithint=file%2c7z
replace \grldr with new 2015-07-16 grldr.
New 2015-07-16 does not work at all! graphics corruption, etc.
![image](https://cloud.githubusercontent.com/assets/1469350/8726281/1e39ca68-2bd1-11e5-887a-1dff35fe7159.png)

**Comment by steve6375** [comment]
Fresh boot with test example
https://onedrive.live.com/redir?resid=8A0F146CC7416BA9!1667&authkey=!AOm6OeG2FNibGgc&ithint=file%2c7z
![image](https://cloud.githubusercontent.com/assets/1469350/8726554/dde1cbc6-2bd2-11e5-81fa-ee2c2d7ef01a.png)
![image](https://cloud.githubusercontent.com/assets/1469350/8726583/07ff77c8-2bd3-11e5-8be1-56eb97974919.png)
Helptext colour is changed 
![image](https://cloud.githubusercontent.com/assets/1469350/8726594/175b56ec-2bd3-11e5-941e-0bcec82a8f98.png)
![image](https://cloud.githubusercontent.com/assets/1469350/8726627/452ad746-2bd3-11e5-8ce8-150dfcc5f417.png)
Both helptext AND  notes both changed
![image](https://cloud.githubusercontent.com/assets/1469350/8726638/5df0ea36-2bd3-11e5-96f8-c7a00e465738.png)

Can use color helptext=0xf or 0xFFFFFF - same result.

What is NOTES? Menu help text or grub4dos help text? 
Maybe names should be  helptext (for title \n menu help text) and  keytext (for grub4dos help with menu keys)

Please give example of  menuset --box command  (not using w=0)  - I cannot make it work.

![image](https://cloud.githubusercontent.com/assets/1469350/8727157/1f43ba4a-2bd6-11e5-8299-69dfdbbdc10f.png)

**Comment by steve6375** [comment]
re. timeout
To sample my menu https://onedrive.live.com/redir?resid=8A0F146CC7416BA9!1667&authkey=!AOm6OeG2FNibGgc&ithint=file%2c7z
add

default 0
timeout 5

Then there should be timeout countdown in seconds on screen - but it is not displayed???

**Comment by yaya2007** [comment]
Link no access. Please send to the mailbox: fjy1@hotmail.com。Contain“graphics corruption”

setmenu   --box x=8 w=30 y=6 h=10 l=2

**Comment by steve6375** [comment]
![image](https://cloud.githubusercontent.com/assets/1469350/8737332/c0a6c3b8-2c18-11e5-9afb-1e6e890cca5f.png)

w=30 does not work,  w=0 works.

**Comment by yaya2007** [comment]
Normal image loading.

setmenu --box x=8 w=30 y=6 h=10 l=2 Although the newspaper is wrong, but already work.Why the newspaper is wrong, I'll check again.

"Both helptext AND notes both changed" "BUT it is on wrong line if page-down in menu"
The problem has been known.

"Notes" is modified as "entry_help", which is appropriate.

**Comment by steve6375** [comment]
Download for 2015-07-16 grldr must be corrupt - can you check download please?

**Comment by steve6375** [comment]
I re-compiled the 2015-07-16 source and grldr still gives same graphics problem.
The problem is caused by the this line in menu.lst
/menusetting.gz   %wdspace% %lnspace% %bdwidth% %tophelp% %noitems% %topstart% %menuw% %rstart%
line. If I remove this line it displays a menu.

**Comment by steve6375** [comment]
setmenu --box x=7 y=8 w=54 h=5 l=1
This works in \menu.lst  but not from command console.

I used
setmenu --box x=7 y=8 w=54 h=5 l=1
setmenu --help=17=15

but there are problems:
![image](https://cloud.githubusercontent.com/assets/1469350/8744573/14f3e854-2c70-11e5-839a-3113e6af59dc.png)
1. entry-help not start at  x=17
2. entry-help only displays one line
 also there should be no helptext lines displayed if \n used in title or iftitle

3. if I add 
default 7
timeout 55
![image](https://cloud.githubusercontent.com/assets/1469350/8744601/5cc87f00-2c70-11e5-93c2-37196460e19e.png)

**Comment by yaya2007** [comment]
"2015-07-14 In menu.lst
set tophelp=13
but 'entry_help' is not on line 13???"
2015-07-16Version:  --notes=[x]=[y]=[line]

"1 entry-help not start at x=17
 2 entry-help only displays one line
 also there should be no helptext lines displayed if \n used in title or iftitle"
 'setmenu --help=17=15'  help  start at x=17; entry-help start at x=16.
The default,entry-help displays 1 lines, and is located in the top 1 rows of help.
Otherwise, you need to set up entry-help .

"3 if I add 
 default 7
 timeout 55"
As already know, there is no change.

**Comment by yaya2007** [comment]
"/menusetting.gz %wdspace% %lnspace% %bdwidth% %tophelp% %noitems% %topstart% %menuw% %rstart%"
I extracted the "menusetting" file, so I didn't observe the error.

**Comment by steve6375** [comment]
New grub4dos 0.4.6a **MUST be backwards compatible** with previous 0.4.5c and older 0.4.6a.
Many people use menuset or menusetting batch file to set menu position.
Default for entry-help should be 4 lines (not 1) to be same as previous versions. 

ReadMe_Grub4dos.txt:
>You may append your help text to the title line. The help text must begin with "\n", for example:
>	title This is the title\nThis is the help text.**\nAnd this is the 2nd line of the help text.**

if title xx\n is used then grub4dos help text should be suppressed and only display entry-help, same as old versions.
New grub4dos should work with menusetting. If not, all new grub4dos menus must be re-written by all users and will now only work with new version and will not work with 0.4.5c or older 0.4.6a!!

If you want to make a non-compatible version of grub4dos, please call it *'grub4yaya'* or something else. Documentation for grub4dos is well known and many people have written menus for grub4dos which will now not work with new version or crash if try to use menusetting. Please make compatible menu system which will work with menusetting.gz or use a different name for grub4dos.

**Comment by yaya2007** [comment]
"New grub4dos 0.4.6a MUST be backwards compatible with previous 0.4.5c and older 0.4.6a."
This is to be, I recognize.

"New grub4dos should work with menusetting."
This requirement is a bit high. Set menu, from the Internet to find, as well as menuset, and so on, whether it is compatible?
"/menusetting.gz %wdspace% %lnspace% %bdwidth% %tophelp% %noitems% %topstart% %menuw% %rstart%"The image can not be loaded, with the current new version of the setting menu is no relationship.

Now the difference is that"if title xx\n is used then grub4dos help text should be suppressed and only display entry-help,”
Some people need help and entry-help exist at the same time.
Do not need help, you can so --help-off shielding, I think it is not compatible with the.

**Comment by steve6375** [comment]
Syntax of setmenu --notes not very clear

maybe change to 
--notes=[x]=[y]=[no. lines]

**Comment by steve6375** [comment]
menuset is in grubutils by chenall
https://code.google.com/p/grubutils/downloads/list


I can add extra code to make Easy2Boot work on old and new versions, but it is not ideal:

set NEWGRUB=
cat --locate="setmenu --param" (md)0x200+0x50 > nul && set NEWGRUB=1
if not exist NEWGRUB /menusetting.gz   %wdspace% %lnspace% %bdwidth% %tophelp% %noitems% %topstart% %menuw% %rstart%
if exist NEWGRUB set /a hstart=%rstart%-2 > nul
if exist NEWGRUB set /a tophelp=%tophelp%+1 > nul
if exist NEWGRUB setmenu --box x=%rstart% y=%topstart% w=%menuw% h=%noitems% l=%bdwidth%
#if exist NEWGRUB setmenu --help=%hstart%=34
if exist NEWGRUB setmenu --notes=%hstart%=%tophelp%=4
if exist NEWGRUB setmenu --help-off
set NEWGRUB= && set hstart=

**Comment by yaya2007** [comment]
Take your advice.
Set 1 old patterns (by default, so that the menu can help disappear), consistent with previous versions;
Set 1 new models (no menu help disappearing)

**Comment by steve6375** [comment]
OK - If setmenu command is used then set new model. ?
Default old model has  4 lines help text?

re. timeout counter - can the number countdown be placed outside of the menu? If using Arabic menus, the text is right-justified - counter number then obscures the text:
![image](https://cloud.githubusercontent.com/assets/1469350/8760664/f8948fc6-2d21-11e5-9585-2e73c657970d.png)

if menu is full width then keep same position as now (inside menu). If menu (start+width) < max-screen-width - 2 then display at far right, *outside* of menu.

How can counter be disabled?

**Comment by steve6375** [comment]
Can password prompt be same colour as 'menu-entry' text and also  right-start in same position as 'menu-entry' text?
Example below has yellow menu-entry text, but 'Password: is white (console text colour) and it's position is far left. If run password from console then current display is OK, but if run password from a menu then colour and position should match 'menu-entry' text - is this possible please?

**Comment by steve6375** [comment]
Problems with 2015-07-24
![image](https://cloud.githubusercontent.com/assets/1469350/8874124/9e8e53ca-3205-11e5-945a-634067556b5e.png)
1 timeout counter in wrong place if default is in 2nd page of menu
and overwrites menu entry - needs to be outside of menu box.
![image](https://cloud.githubusercontent.com/assets/1469350/8874229/e4332508-3206-11e5-955c-4c623078c2db.png)
Suggest colour of timeout counter is  'normal' colour so that it stands out against highlight colour?

2 Password prompt not aligned under menu 
(and in standard/console colour not 'menu-entry' colour.
![image](https://cloud.githubusercontent.com/assets/1469350/8874190/631ea988-3206-11e5-9b41-c06abbbcac51.png)

3 Improve help for setmenu
![image](https://cloud.githubusercontent.com/assets/1469350/8874253/27509df2-3207-11e5-8a10-29db542d233a.png)
suggest 'lines'  or 'number of lines' or 'no. lines'

4 New version incompatible with menusetting.gz utility.

**Comment by yaya2007** [comment]
Can you send a menu containing the language of Arabia to my mailbox?

**Comment by steve6375** [comment]
Hi yaya

MenuArabic.lst is how an Egyption would write the menu.lst using Notepad -
BUT it does not display in correct order under grub4dos.

To be displayed correctly in grub4dos, the text needs to be reversed.
They use Fribidi.exe to reverse the Arabic glyphs

So it is converted to  menurev.lst

MenuArabic.lst  >>>>>> (Fribidi.exe  >>>>>>> menurev.lst



But this does not really matter for grub4dos, grub4dos just needs to align
the menu to the right by padding each menu entry with spaces


e.g.  | is menu border...

| abcde                                                   |

when displayed in menu should be

|                                                   abcde|


See http://reboot.pro/topic/16340-graphicsmode-syntax/page-2#entry193544

e.g. if menu width is 60 characters, then menu entry for abcde should be

<55 spaces>abcde


if menu width is 30 characters, then menu entry for abcdef should be

<25 spaces>abcde


So you do not need to worry about reversing the characters because
Fribide.exe can process the characters.

A good feature would be to right-align the menu text according to the menu
width.


If possible, the next step would be to do what fribidi.exe does  (reverse
Arabic characters but not non-Arabic characters)  - but this may be
difficult for you???

Steve



Fribidi.7z.rename >>>  Fribisi.7z   to  unpack

**Comment by steve6375** [comment]
Demo menu at
http://files.easy2boot.com/200001245-9453c9647d/menuArabicDemo.lst

**Comment by yaya2007** [comment]
Now the situation is:
1.Compatible menusetting.gz;
2.Adjust the position and color of the password;
3.Fixed second page down timing error;
4.Added right align;
Test grldr is located in the following, I do not know whether to visit.
http://bbs.wuyou.net/forum.php?mod=viewthread&tid=369720&extra=page%3D1
#1

**Comment by steve6375** [comment]
I tested new version - Good job!

1.Compatible menusetting.gz;  OK Now :-)
2.Adjust the position and color of the password;   
Problems:
**2a text needs to be moved > 1 space**
**2b Menu help text needs to be cleared - see Demo**
![image](https://cloud.githubusercontent.com/assets/1469350/8938541/1e818e54-3557-11e5-9767-b2d7a216779d.png)

3.Fixed second page down timing error;  OK
What are rules now?

4.Added right align;
**This does not work if the menu text has embedded RTF codes - see example file.**
![image](https://cloud.githubusercontent.com/assets/1469350/8938656/d65a2324-3557-11e5-84a1-b8f924f5a67d.png)

http://files.easy2boot.com/200001246-1389a1582d/menuArabicDemo1.lst

**Comment by steve6375** [comment]
P.S. In help text - suggest use * to indicate defaults
![image](https://cloud.githubusercontent.com/assets/1469350/8938872/0359632a-3559-11e5-8cf6-d101bb9df745.png)


re.
setmenu --string=10=30=0xFFFFFF00FF0000="HELLO"
This does not show white background ???
![image](https://cloud.githubusercontent.com/assets/1469350/8939000/e637754c-3559-11e5-95fc-e7227cd6e96a.png)
e.g. color helptext=0xFFFFFF00FF0000
shows white background

**Comment by steve6375** [comment]
P.S. Please can we have a setmenu command to disable the countdown timer?

**Comment by steve6375** [comment]
How about add extra setmenu command???

setmenu --timeout-pos=[x]=[y]

if y not specified then use menu entry line  (x determines position on line)
if x=-1 then disable countdown

**Comment by yaya2007** [comment]
"In help text - suggest use * to indicate defaults" and "right align" and "Menu help text and menu-entry text needs to be cleared " error has been corrected.

No timeout, or "timeout" ,or "timeout -1" do not show countdown.

"setmenu --string=10=30=0xFFFFFF00FF0000="HELLO" "Only support the foreground.
Align left, front empty 10;Right align, back empty 10.

Test grldr download address as before.

**Comment by steve6375** [comment]
Still  problems with right-align.
Please download http://files.easy2boot.com/200001246-1389a1582d/menuArabicDemo1.lst
![image](https://cloud.githubusercontent.com/assets/1469350/8959541/55540b1c-3603-11e5-8da3-6faf35cd4378.png)
suggest clear ALL lines of help text and menu-entry text before password prompt is displayed.

also if add
setmenu --auto-num
![image](https://cloud.githubusercontent.com/assets/1469350/8959462/df0876aa-3602-11e5-8f9d-2c4c346f1d35.png)

I would like to position countdown timer on menu using 
setmenu --timeout-pos=[x]=[y]=[color]

![image](https://cloud.githubusercontent.com/assets/1469350/8959661/11a2fc9c-3604-11e5-9e89-93cb81266eab.png)

e.g. 
default 2
timeout 10
setmenu --timeout-pos=70=36=0xFF0000  (x=70 y=36 colour=red)

setmenu --timeout-pos=-1   (disable)

setmenu --timeout-pos=70=*=0xFF0000    (position at x=70 on same line as menu entry, colour red)

not ***disable*** timeout, but  disable the counter or move it and  define colour

**Comment by steve6375** [comment]
P.S. How to turn auto-numbering off once it has been turned on?
setmenu --auto-num-off ???

**Comment by yaya2007** [comment]
Right aligned bug exclusion.
Increased --auto-num-on and --auto-num-off parameters.
"setmenu --timeout-pos=70=36=0xFF0000 (x=70 y=36 colour=red)
setmenu --timeout-pos=-1 (disable)
setmenu --timeout-pos=70=*=0xFF0000 (position at x=70 on same line as menu entry, colour red)"
Unclear,The necessity of such a setting.

**Comment by steve6375** [comment]
New 2015-07-30 - looking much better.
Issues:
1. If have  title abc[space][space][space]\nfred[space][space][space]

and right-align, then menu entry is not right-aligned - need to ignores spaces?
![image](https://cloud.githubusercontent.com/assets/1469350/8979381/1958faca-36a1-11e5-8efe-83c75729c768.png)
![image](https://cloud.githubusercontent.com/assets/1469350/8979396/318bf4ee-36a1-11e5-84ad-500b9c1cdd16.png)

2. If timeout set and then hit cursor key, background square left behind
![image](https://cloud.githubusercontent.com/assets/1469350/8979430/7f482d06-36a1-11e5-8a34-021f47b7a1e1.png)

3. re. setmenu --timeoutpos
It would be nice to have the option to hide the countdown and change it's position and colour.
Also, if a menu line is long or just fits the width of the menu, the countdown can obscure the menu text.
![image](https://cloud.githubusercontent.com/assets/1469350/8980122/390acad8-36a6-11e5-9757-8249692a2727.png)
I would like option to move countdown to top-right of menu or maybe bottom right or outside of menu border.

**Comment by yaya2007** [comment]
"1. If have title abc[space][space][space]\nfred[space][space][space]"
Right alignment does have a problem. It's not a difficult thing to get rid of these spaces. Because the menu is allowed to have spaces. For example, the menu item before the first character of the space, can be judged as useless; but filling the space can achieve the effect of the right, at this time it is useful.

"1.If timeout set and then hit cursor key, background square left behind"
To the background color, there is no problem.
color yellow/cyan black/cyan 

"2.re. setmenu --timeoutpos"
I think about it, whether it is arbitrary.

**Comment by steve6375** [comment]
many people use a space after title and before \n because it is easier to read.

title xxxx \nyyyyyy

this leaves space after xxxx  if right-align.

If they really want spaces they can use

title xxxx\x20\x20\x20\nyyyyyy

**Comment by yaya2007** [comment]
Timeout location, color can be set.
After the string to the space, the right can be eliminated.

**Comment by steve6375** [comment]
Good! thanks. :-)

**Comment by steve6375** [comment]
Sorry, but
setmenu --right-align
title abcd\x20\x20
does not work now so user cannot shift menu entry.
Can right-align not translate \x20 to space before aligning?
I expected
title abcd[space][space]   >>         abcd|
title abcd\x20\x20             >>      abcd  |

**Comment by steve6375** [comment]
bug - causes crash of menu if set help text outside display areas (to hide helptext)
if 800x600 mode
setmenu --entryhelp-keyhelp-coexist
setmenu --keyhelp=101=30

values for x over 100 causes crash
y can be 200 and is OK, but x>100 causes crash.

**Comment by yaya2007** [comment]
The pre - processing program turns \0x20 into 0. What is the place to do? I am not clear. If the right alignment is necessary to display 0 of the end of the string, it is restored to the previous state, i.e., there is a blank display. Can be controlled by the menu.

Do not display the keyboard to help, set the y=38 --keyhelp.

**Comment by steve6375** [comment]
setmenu --keyhelp=101=30  should not crash grub4dos.
 e.g. test this menu (splashimage is optional)

graphicsmode -1 800
splashimage /_ISO/bunny2.bmp
setmenu --entryhelp-keyhelp-coexist
setmenu --keyhelp=101=30

title test
reboot

>>> CRASH!

re. spaces

We should have a way to add spaces in right-aligned menus.
e.g.
setmenu --right-align
title --oOo--                 \n
root

to make a menu separator line.  So if no way to add spaces in title for right-align, we must go back to the previous method to make this work.

**Comment by yaya2007** [comment]
New test version, added --keyhelp=[x]=0 is not shown to display keyhelp(in --entryhelp-keyhelp-coexist),In addition,To restore the previous state, do not remove the space at the end of the string.

**Comment by steve6375** [comment]
2015-07-31
![image](https://cloud.githubusercontent.com/assets/1469350/9005876/c4230d32-3779-11e5-9147-d46a2ab2324f.png)
Is keyhelp--timeout=   correct ???  missing /n ??


setmenu --keyhelp=101=30  still crashes grub4dos (see above) - should be prevented.

**Comment by yaya2007** [comment]
“setmenu --keyhelp=101=30 ”Has been resolved.
--keyhelp when y> maximum line, do not show keyhelp. So the y=0 option is revoked.
.

**Comment by steve6375** [comment]
setmenu --keyhelp=10=40

suppresses keyhelp, but position of entryhelp is changed to  y=0  !!

![image](https://cloud.githubusercontent.com/assets/1469350/9012197/e99912f6-37aa-11e5-9eb6-a611a32354bd.png)

**Comment by yaya2007** [comment]
I'm sorry! Test version has been corrected.

**Comment by steve6375** [comment]
Still a problem (with or without right-align)

graphicsmode -1 800 600 24:32
font /_ISO/e2b/grub/unifont.hex.gz
set tophelp=30
set menuw=65
set topstart=5
set rstart=10
set noitems=25
setmenu --box x=%rstart% y=%topstart% w=%menuw% h=%noitems% l=1
setmenu --entryhelp-keyhelp-coexist && setmenu --keyhelp=1=60
setmenu --right-align

title ABCD\nABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ
reboot

menuentry is moved by setmenu --keyhelp=1=60
![image](https://cloud.githubusercontent.com/assets/1469350/9021255/358431ce-3831-11e5-9332-b20d35c82847.png)

![image](https://cloud.githubusercontent.com/assets/1469350/9021253/d78e767e-3830-11e5-9778-0d970a45a064.png)

**Comment by steve6375** [comment]
Also, only one line of menuentry help text is shown. Default should be 4 lines (same as old versions).

**Comment by yaya2007** [comment]
In the old mode, help the start and end of the menu to determine the border.
In the new model, to help in the show, margin determined by X.

**Comment by steve6375** [comment]
It is not compatible. Many menus are designed to show text under menu not across whole screen (design of wallpaper)
see
http://files.easy2boot.com/system_preview_detail_200000092-a241da3387-public/e2bMAC.jpg
default helpmenuentry should be under menu and within border as before.
Maybe add option to set x-start and x-end?
Also should be 4 lines allowed by default.

**Comment by yaya2007** [comment]
Maybe " set x-start and x-end" is more clear.
The "Capture.PNG" is left aligned, the string is not long, no top to the right B boundary, can not explain the problem. Current settings will be the way.
"E2bMAC.jpg" at the bottom of the yellow and red help, seems to be right in the mode, the string starts to insert the space. The current model can be done, not contradictory.
"Entryhelp" can specify the number of rows, 3 rows, and 5 rows, at random. If the default 4 lines, plus the "keyhelp", by default, help with the 8 line!
The impact is beautiful, is aligned, is the beginning of the string.

**Comment by steve6375** [comment]
Using menusetting.gz and not using new setmenu command (i.e. old menu.lst) 
EXAMPLES

0.4.5c
![image](https://cloud.githubusercontent.com/assets/1469350/9022150/6d90fa86-3861-11e5-9283-c13e5cd6afac.png)
New 0.4.6a
![image](https://cloud.githubusercontent.com/assets/1469350/9022154/993ee03a-3861-11e5-97d3-c7d7621275d3.png)

Note menuhelptext line is shorter and only one line.
It is important for new version to be compatible. If user wants longer lines then they can change using setmenu. But default behaviour should be same as all older 0.4.5c and older 0.4.6a to maintain compatibility.

1024 bitmap

Old 0.4.5c
![image](https://cloud.githubusercontent.com/assets/1469350/9022160/41a77d2c-3862-11e5-9872-943c8015534b.png)


New 0.4.6a
![image](https://cloud.githubusercontent.com/assets/1469350/9022159/2adeaab6-3862-11e5-8573-0d55ae1b14eb.png)
Note menuhelptext cut off

**Comment by yaya2007** [comment]
Got it

**Comment by steve6375** [comment]
one more compatibility issue:  old color command was
color normal highlight **helptext** heading
or
color helptext=0xFF00FF

This set the color of the helptext **and** entryhelp text. This means the entryhelp colour is not changed and so is incompatible. Now, with new grub4dos, I suggest that color helptext=xxx  will set **both** the menuhelp and entryhelp text colour but ONLY if a color entryhelp command has NOT been used before.

***pseudocode***

declare internal variable EHELP

**color entryhelp=0x1f**
change entryhelp colour to 0x1f
set EHELP=1

**color helptext**
change helptext colour to 0x1f
if EHELP <> 1 change entryhelp colour to 0x1f

I think this would be compatible but also work for new color entryhelp usage.

P.S. Would be useful if  'color helptext=?' returned the current value of helptext colour, 'color entryhelp=?' returned current value of entryhelp colour, etc. so we can get current colour values?

**Comment by steve6375** [comment]
by default number of lines for entryhelp = 4 please? OK?
(entryhelp-cover-keyhelp is default already)

**Comment by yaya2007** [comment]
"""by default number of lines for entryhelp = 4 please? OK?"
OK

Before,no distinction keyhelp and entryhelp.So, 'color helptext'='color keyhelp'='color entryhelp'.
Now,distinction keyhelp and entryhelp.So,'color helptext' only one of 'color keyhelp' or 'color entryhelp'.
Your suggestion is:'color helptext' = 'color entryhelp'?'color keyhelp' other settings?

**Comment by steve6375** [comment]
My suggestion is as above - please see pseudocode example.
I think this is good solution

in grub4dos c code:

declare internal variable EHELP

color entryhelp=0x1f
change entryhelp colour to 0x1f
EHELP=1

color helptext=0x1e
change helptext colour to 0x1e
if EHELP <> 1 change entryhelp colour to 0x1e

This means old menu.lst user menus will work as before, but new user code using entryhelp and helptext color commands will also work as expected.
Do you understand?

**Comment by steve6375** [comment]
e.g.
color helptext=xxx   >> both keyhelp and helptext change
color entryhelp=xxx  >> only entryhelp changes
color helptext=xxx    >> only helptext changes because of previous entryhelp command

**Comment by yaya2007** [comment]
Got it

**Comment by yaya2007** [comment]
Parametric version has been uploaded. Should be perfected.

**Comment by steve6375** [comment]
![image](https://cloud.githubusercontent.com/assets/1469350/9055474/54cd66e6-3a83-11e5-89e1-729100652a45.png)

Also, menusetting.gz does not change line spacing now
REM word_spacing line_spacing border_width top_help number_of_items_in_menu top_start menu_width right_start_pos_of_menu
set wdspace=0
**set lnspace=7**
set bdwidth=0
set rstart=55
set menuw=85
set topstart=8
set noitems=12
set tophelp=22
/%grub%/menusetting.gz   %wdspace% %lnspace% %bdwidth% %tophelp% %noitems% %topstart% %menuw% %rstart%

Does not change line spacing - has internal variable position changed? It also seems to cause problems with setting a timeout. Maybe menusetting.gz is changing wrong internal variable now?
(not tested wdspace setting).

**Comment by steve6375** [comment]
Problem with lines with no \n in title

graphicsmode -1 800 600 24:32
font /_ISO/e2b/grub/unifont.hex.gz
set tophelp=30
set menuw=65
set topstart=5
set rstart=10
set noitems=25
/_ISO/e2b/grub/menusetting.gz n n 1 %tophelp% %noitems% %topstart% %menuw% %rstart%
**setmenu --keyhelp=60=0x1e**

title reboot\nfred    
reboot
title NOMENUHELP 
boot
title reboot\nfred    
reboot

whenNOMENUHELP is selected, display is cleared!

**Comment by yaya2007** [comment]
"help setmenu" and "setmenu --keyhelp=60=0x1e" Correction.

"set lnspace=7"I do not know what reason. There appears to be no external interface between the character spacing and row spacing.

**Comment by steve6375** [comment]
menusetting.gz uses the command  'terminal' - e.g.

terminal --font-spacing=0:7

This works in 0.4.5c and 0.4.6a 2015-06-05  but not on new 0.4.6a

**Comment by yaya2007** [comment]
Has been amended

**Comment by steve6375** [comment]
New version looks good in testing so far :-)

**Comment by steve6375** [comment]
Query
How can I change the colour of the timeout countdown number without changing it's position?

setmenu --timeout=*=*=0xFF00FF

??

**Comment by yaya2007** [comment]
Current cannot

**Comment by yaya2007** [comment]
Test versions have been implemented
setmenu --timeout=0=0=0xFF00FF

**Comment by steve6375** [comment]
looks OK :-)
color must be 32-bit value. Can you specify this in help text please?

also maybe change help text
[y_offset]=0* entryhelp text covers keyhelp text
[y_offset]!=0 keyhelp is y_offset lines below entryhelp
[y_offset]<=4 number of entryhelp lines displayed

Should setmenu --help=0=0=30   centre the text ???  Does not seem to work?

**Comment by yaya2007** [comment]
30 = 0xRRGGBB = 0x00001e  
Black background can be seen in some l blue figures.

**Comment by steve6375** [comment]
--help
![image](https://cloud.githubusercontent.com/assets/1469350/9150321/61fc30b8-3dcb-11e5-915a-726b6f7d8a9f.png)

**Comment by yaya2007** [comment]
echo -rrggbb

**Comment by steve6375** [comment]
maybe better??

--help=[x]=[w]=[y]
Note: [x]=0* determined by menu start, [w]=0 determined by menu width.

**Comment by yaya2007** [comment]
Seems like this better
--help=[x]=[w]=[y]
 Note: [x]=0* Menu border as boundary, [w]=0 Each line of the character minus 2x.

**Comment by steve6375** [comment]
Maybe:

--help=[x]=[w]=[y]
Note: [x]=0* Under menu, [x]<>0 and [w]=0 Entire display width minus 2x.

**Comment by yaya2007** [comment]
Adopt, thank you!

**Comment by steve6375** [comment]
Thanks
