### ISSUE TITLE
Request: display animated picture

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#90]
I would like to display a sequence of animated pictures or show a small cartoon using grub4dos.
I have managed to do this by using splashimage and clear - see http://rmprepusb.blogspot.co.uk/2016/01/display-animated-picture-in-grub4dos.html
However, the 'clear' takes too long and there is always a black screen in between the pictures.
Is there a way to display bitmaps in rapid succession in grub4dos?
It would also be nice to be able to specify an x,y location for splashimage so that smaller bitmaps (e.g. 200x200) could be overlaid onto a larger 800x600 bitmap so that only a small area is updated with an animated graphic after loading a larger wallpaper bitmap.
It would also be nice to be able to display animated .gifs too (perhaps using a grub4dos utility?).
Any ideas welcome!

**Comment by steve6375** [comment]
Is there a way to display a sequence of bmp files please without having to use the clear command?

https://onedrive.live.com/redir?resid=8A0F146CC7416BA9!2179&authkey=!AKDgDMlcRRP1Gxg&ithint=file%2czip

**Comment by yaya2007** [comment]
May be used to achieve. Can you provide 'sequence of bmp files' in order to develop the test?
The above link cannot be opened in the mainland.

**Comment by steve6375** [comment]
[Animated_BritneyLZMA_v2.zip](https://github.com/chenall/grub4dos/files/84020/Animated_BritneyLZMA_v2.zip)

**Comment by yaya2007** [comment]
Very interesting!
It seems that the menu appears, can not reproduce the animation.

**Comment by steve6375** [comment]
It needs to be called as a batch file
please try new version
[Animated_Britney_Test.zip](https://github.com/chenall/grub4dos/files/85432/Animated_Britney_Test.zip)

**Comment by yaya2007** [comment]
Very good! Can display animation in menu items.

In the menu item background picture, displays the small, simple animation, very interesting.
I wonder if it is necessary.

**Comment by steve6375** [comment]
The test code has two problems though
1. The screen is blanked/cleared after each picture is displayed
2. The graphicsmode is changed after each picture is displayed which causes the monitor to lose sync, on an HDMI monitor, the monitor takes several seconds to re-sync between each picture

What I would like to know is how I can prevent these two problems so that I can display a sequence of bitmaps.

**Comment by yaya2007** [comment]
"which causes the monitor to lose sync, on an HDMI monitor, the monitor takes several seconds to re-sync between each picture"
Do not understand

**Comment by steve6375** [comment]
Did you try it on a PC with a hdmi monitor?
I mean real system, not a VM. Splashimage seems to change graphicsmode twice and this causes the monitor to lose sync for about 2 seconds!

**Comment by steve6375** [comment]
Thanks for the new splashimage support.
I tried splashimage --offset=300=300 using a smaller 203x281pixel icon bmp file.
graphicsmode -1 800 600
splashimage /My800x600.bmp
splashimage --offset=300=300 /icon.bmp

The small image is stretched/distorted. Am I doing something wrong?
![image](https://cloud.githubusercontent.com/assets/1469350/12536799/00ad0b72-c2a8-11e5-9a24-4e2391d2a215.png)

**Comment by yaya2007** [comment]
I have no problem here.Upload icon.bmp.

**Comment by steve6375** [comment]
It seems to depend on what is in the bmp ???
![image](https://cloud.githubusercontent.com/assets/1469350/12674193/83c923a4-c679-11e5-8633-bf887dd1a1e1.png)

[G.zip](https://github.com/chenall/grub4dos/files/109625/G.zip)

**Comment by steve6375** [comment]
P.S. if  --offset is used, then any following splashimage uses that offset
e.g.
splashimage --offset=200=200 /icon.bmp
splashimage /picture800x600.bmp

The second bitmap is displayed at 200 200  - should be at 0 0

**Comment by yaya2007** [comment]
iconBAD.bmp and iconOK.bmp OK!

**Comment by steve6375** [comment]
/menu.lst

```
graphicsmode -1 800
splashimage --offset=300=300 /iconok.bmp
splashimage --offset=100=100 /iconbad.bmp

title TEST
reboot

```

![image](https://cloud.githubusercontent.com/assets/1469350/12676032/cb7b37b6-c686-11e5-822e-be5dca76ed9c.png)

**Comment by steve6375** [comment]
Same menu booted from EeePC instead of VBox
![image](https://cloud.githubusercontent.com/assets/1469350/12676108/816a71e0-c687-11e5-9d2e-0a8ee92124f2.png)

**Comment by steve6375** [comment]
I use grldr from download zip file - is it same version as you?

**Comment by steve6375** [comment]
P.S. Is there a splashimage command to fill the graphics memory with a single colour? Might be useful? e.g. splashimage --fillcolor=0xrrggbb --offset=100=200 /icon.bmp

**Comment by yaya2007** [comment]
First, loading a whole background image is normal.

**Comment by yaya2007** [comment]
> The small image is stretched/distorted
This is how to return a responsibility?

**Comment by yaya2007** [comment]
"The small image is stretched/distorted"
This is how to return a responsibility?

**Comment by steve6375** [comment]
Sorry - I don't understand??

**Comment by steve6375** [comment]
Yes, but with new offset parameter, we can now just have a small logo and fill graphics memory with a single colour. This means faster menu (no large .bmp file to load).
Presumably the graphicsmode command does not fill memory with 00's = black?

**Comment by yaya2007** [comment]
"Presumably the graphicsmode command does not fill memory with 00's = black?"
yes

**Comment by 2012yaya2007** [comment]
http://bbs.wuyou.net/forum.php?mod=viewthread&tid=369720&extra=page%3D1

**Comment by steve6375** [comment]
Thanks for the new features! :+1: 

I think Help text is wrong

> Type [type]: bit0-3: 0/1/2 = empty / time / cycle

This is incorrect! Should be...???

> Type [type]: bit0-3: 0/1/2 = cancel / cycle / time

0 = uninstall
1 = cycle
2 = time

Also, I have a problem with cycle with Easy2Boot.
If I load a bitmap splashimage and use cycle, then the animated picture does not appear on menu, but, if I press Down Arrow key or Up Arrow  Key then the the picture appears. Each time I press Up/Down the next picture in sequence appears.
This problem is caused by loading **hotkey** grub4dos utility. So hotkey stops animation.

**Comment by steve6375** [comment]
splashimage with cycle displays 
Loading Splashimage....
![image](https://cloud.githubusercontent.com/assets/1469350/13046602/9c870356-d3d1-11e5-9c48-9912e3ab938d.png)

unless debug 0 is used.
Can message be suppressed for animated command please?

```
# must unload hotkey as stops animation in cycle mode
hotkey -u
set trans=0x10 && set once=0x2 && set cycle=0x1
set /A type=%cycle% + %trans%
set delay=0x1
set end=0x1a
set offx=20
set offy=90
set P=/BritneyLZMA/frame-01.bmp
#debug 0
splashimage --animated=%type%=%delay%=%end%=%offx%=%offy%=%P% > nul
clear
title TEST1
root ()

```

**Comment by 2012yaya2007** [comment]
I think carefully, or the use of "debug=0" as a good.

**Comment by steve6375** [comment]
```
splashimage /wallpaper.bmp
splashimage --animated=1=xxxxxxx
```

this works, but

```
splashimage --animated=1=xxxxxxx
splashimage /wallpaper.bmp
```

does not work. The cycle animation does not start if followed by a normal splashimage command.

where xxxx is a valid command string of parameters.

**Comment by 2012yaya2007** [comment]
bit0-3:  0/1/2=invalid/single/repeat   bit4-7:   0/1=normal/keyer
how?

**Comment by 2012yaya2007** [comment]
Please follow the "splashimage --animated=[type]=[delay]=[sequence_num]=[offset_x]=[offset_y]=[name]",Don't lean.
1.Parameter has no default value.
2.Type has been retained.

**Comment by steve6375** [comment]
type
0=disable (clears previous animation)
**1=repeat
2=once**
+0x10=transparent

This is what I have found when testing. It does not match documentation.

**Comment by steve6375** [comment]
It would be nice to repeat the animation more than once.
Is it possible to specify number of loops for 'once'
maybe change type definition?

bits 0-3= number cycles 1-15 (if 0 then disable previous animation)
bit 4 = transparent
bit 5 = infinite cycle

e.g. 0x31 = cycle always transparent, 0x06 = show 6 times, 0x00 = disable previous cycle animation

or maybe:
bits 0-3 = number cycles 1-15 (if 0 = infinite)
bit 4 = transparent
bit 5 = disable previous infinite cycle

??

**Comment by 2012yaya2007** [comment]
type: bit0-3:  0/1/2=disable/repeat/once
         bit4-7:  0/1=disable/transparent_background

**Comment by steve6375** [comment]
How can I cycle 3 times?
If I repeat splashimage --animated  then it is not smooth.
I would like to show user animation for n cycles.

**Comment by 2012yaya2007** [comment]
type: bit0-2: cycle times(1-7times)  bit3:transparent_background
         bit4-7:  1/2=repeat/cycle
         00=disable

**Comment by steve6375** [comment]
bit0-2: cycle 1-7 times
bit 3: transparent
bit 4: infinite cycle
type=0: disable

or maybe 
bit0-3: cycle 1-15 times
bit 4: transparent
bit 5: infinite cycle

?? easier to work in hex  +0x10 +0x20 is easier for user ??

P.S. For
splashimage --offset=730=40 /_ISO/E2B.bmp
a transparent_background option might be useful? splashimage **--toffset**=730=40 /_ISO/E2B.bmp  ???

**Comment by 2012yaya2007** [comment]
bit0-3: cycle 1-15 times
 bit 4: transparent
 bit 5: infinite cycle
type=0: disable
ok

splashimage --toffset=730=40 /_ISO/E2B.bmp 
Can not

**Comment by steve6375** [comment]
splashimage --animated=0x11=1=1=750=540=/_ISO/E2B01.bmp
this works if just use 1 for number of bitmaps. = transparent

**Comment by steve6375** [comment]
_Maybe use rule
if  number=1 then use exact filename
splashimage --animated=0x11=1=**1**=750=540=/_ISO/E2B.bmp - displays E2B.bmp transparent
splashimage --animated=0x01=1=**1**=350=540=/_ISO/E2B05.bmp   - displays E2B05.bmp

then no need for splashimage --offset  command?_

**Comment by steve6375** [comment]
Actually --animated for 1 picture does not work correctly if hotkey, so please keep --offset command!

**Comment by 2012yaya2007** [comment]
If you do not enter the offset, that is, the previous use of.

**Comment by 2012yaya2007** [comment]
1 transparent +1 opaque+1 transparent +1 opaque....
Need to be so complicated?

**Comment by steve6375** [comment]
Sorry, I don't understand you???
bit0-3: cycle 1-15 times
bit 4: transparent
bit 5: infinite cycle
type=0x00: disable
is OK for me.

**Comment by steve6375** [comment]
If have menu.lst:
splashimage /_ISO/wallpaper.bmp
splashimage --offset=730=40 /_ISO/E2B.bmp
splashimage --offset=750=540 /_ISO/E2B.bmp
title Show menu 2
configfile /menu2.cfg

When I go to menu2.cfg, the two E2B.bmp are still visible - which is OK.
But - how can I remove them without affecting the wallpaper?

e.g.
menu2.cfg
=========
splashimage --offset=cancel
splashimage --offset=730=40 /_ISO/E2B_menu2.bmp

**Comment by 2012yaya2007** [comment]
"type: bit 0-3:times  bit 4:play  bit 5:repeat forever\n"
  "      bit 7:transparent background      type=00:disable\n"

paly n times: Animation and menu key sharing time
repeat forever: Animation exclusive time

**Comment by steve6375** [comment]
Good :+1:

**Comment by steve6375** [comment]
I think small bug in cycle code
If display animation of 9 images 01 to 09, then **last** frame09.bmp has no delay so user cannot see it unless it is left on screen.
e.g.
splashimage --animated=2=15=09=350=250=/frame01.bmp
splashimage /wallpaper.bmp

Then user does not see frame09.bmp because there is no delay after it is displayed.
Code should be 
1. display frame
2. delay
3. loop or exit

**Comment by steve6375** [comment]
Also, if file not found then abort loop.

**Comment by steve6375** [comment]
For transparent, if background is black (first pixel is rgb 0x000000) then transparent does not work.
Does first pixel need to be non-zero? How does transparent decide on background colour?

**Comment by steve6375** [comment]
re. splashimage help
name must be xxxxx01.xxx  (not xxxx**-**01.xxx)
'sequence_num'  maybe better described as 'last_num'  ??

**Comment by 2012yaya2007** [comment]
Please test
http://bbs.wuyou.net/forum.php?mod=viewthread&tid=369720&extra=&page=1

**Comment by 2012yaya2007** [comment]
> name must be xxxxx01.xxx (not xxxx-01.xxx)
> Already corrected
> 
> 'sequence_num' maybe better described as 'last_num' ??
> agree Next amendment

**Comment by 2012yaya2007** [comment]
background is black (first pixel is rgb 0x000000) ,available to work.
I get the first pixel.
You use "WinHex" to see if the first pixel is 0

**Comment by steve6375** [comment]
Thanks for new version, a few problems/questions
1. If first pixel is rgb=0x000001 then transparent does not work. _ZIP attached below_.
2. hotkey disables repeat forever animation (hotkey -A)
3. must specify a valid file to stop animation - why not just splashimage --animated=0 ?
4. Why is play bit (0x10) required?  Why not just use bit 7 (0x80) = 0 and type<>0?
5. If bad file spec  (e.g. 08.bmp is missing) then loop does not abort
6. if splashimage --offset has bad filespec then menu not displayed
[E2B.zip](https://github.com/chenall/grub4dos/files/137661/E2B.zip)

**Comment by steve6375** [comment]
Strange issue: 
using splashimage --offset command
.jpg displays OK, but .bmp does not!
[bitmaps.zip](https://github.com/chenall/grub4dos/files/138175/bitmaps.zip)
![image](https://cloud.githubusercontent.com/assets/1469350/13179358/7d21a0d2-d71b-11e5-8e19-4636f372a440.png)

**Comment by 2012yaya2007** [comment]
See examples
http://bbs.wuyou.net/forum.php?mod=viewthread&tid=369720&extra=&page=1

**Comment by steve6375** [comment]
Thanks! Looking better. Issues below in bold still  not fixed  though
1. If first pixel is rgb=0x000001 then transparent does not work.  FIXED
**2. hotkey utility disables repeat forever animation (hotkey -A)**
3. must specify a valid file to stop animation - why not just splashimage --animated=0 ? FIXED
4. Why is play bit (0x10) required? Why not just use bit 7 (0x80) = 0 and type<>0? FIXED
**5. If bad file spec (e.g. 08.bmp is missing) then loop does not abort (blanks menu)**
**6. if splashimage --offset has bad filespec then menu not displayed**

**Comment by steve6375** [comment]
For --offset function, is it possible to have a transparent function of RGB=0 (black) = transparent?
e.g. 
splashimage --toffset=0=600 /filewithblackedges.bmp

This will allow us to stamp lettering, etc. without square edges. If very difficult then do not worry.

Main issue is hotkey stops infinite animation on menu.

**Comment by steve6375** [comment]
[Hotkey_Test.zip](https://github.com/chenall/grub4dos/files/139613/Hotkey_Test.zip)

**Comment by steve6375** [comment]
Is there a new hotkey? I just noticed 2015-04-08 version says it is outdated??

debug 2
echo run hotkey
hotkey -A
pause

![image](https://cloud.githubusercontent.com/assets/1469350/13202913/bcff420e-d8a1-11e5-9fc8-40d73378b18d.png)

**Comment by steve6375** [comment]
Just noticed another issue.
If splashimage --animated (play n cycles) is used, then the cursor mode is changed so that the background is displayed and then any console text is seen on top of the background.
I think you need to preserve and restore  the current cursor state?

**Comment by 2012yaya2007** [comment]
Do you use a previous version of the test.
1,3,4 Already solved.

**Comment by 2012yaya2007** [comment]
See examples
http://bbs.wuyou.net/forum.php?mod=viewthread&tid=369720&extra=&page=1

Need to modify the hotkey to support the animation.
Hotkey source?Copy with the label!.

**Comment by steve6375** [comment]
http://grub4dos.chenall.net/categories/utils/

**Comment by steve6375** [comment]
Also two old minor issues on hotkey
https://github.com/chenall/grubutils/issues

**Comment by 2012yaya2007** [comment]
Use the hotkey, you can display the animation!

**Comment by steve6375** [comment]
great! :+1:  Thank you.
bad files spec issues fixed
hotkey issue fixed

Problems still though...
1. Animation still plays in command prompt and in edit menu, etc.!!
2. 'Loading splashimage...' is sent to console many times if infinite display - should only display message if debug = 2.
3. console cursor is set to x,y=0,0 -  even if debug=0, should preserve x,y cursor position
4. cursor state not preserved after play n cycles (background visible after play and console text overwrites background). I can fix this using call Fn.70 2 after splashimage --animated  but splashimage should preserve cursor state.

**Comment by steve6375** [comment]
P.S.  Is it possible for infinite cycle to hold frames in memory?
Maybe allocate fixed size of buffer per frame.
If .bmp too big or if too many frames then just run from a file.
This could be limited to small 'sprite' sequences only?
It ensures delay is not dependent on drive speed + does not constantly access drive.

**Comment by steve6375** [comment]
Help splashimage is wrong (space before FILE is now invalid)
--offset=[x]=[y] FILE
should be:
--offset=[x]=[y]**=**FILE

**Comment by 2012yaya2007** [comment]
"This could be limited to small 'sprite' sequences only?"
too troublesome

1,2,3,4 See examples

**Comment by steve6375** [comment]
Thanks!
On commandline debug is always 1 - even if set to 0 or 2 in the menu. Is this expected/correct behaviour?
Can you implement storing frames in memory at all? Even if limitations?

**Comment by 2012yaya2007** [comment]
"On commandline debug is always 1 - even if set to 0 or 2 in the menu. Is this expected/correct behaviour?"
I don't know.

"Can you implement storing frames in memory at all? Even if limitations?"
what are the benefits?

**Comment by steve6375** [comment]
Currently, when infinite frames are played, the files are loaded from disk all the time. This takes time and delay depends on the speed of the drive (e.g. a slow flash drive takes longer and so animation plays slower).
Also, if we change the drive mapping, the animation stops (e.g. map (hd1) (hd0), map --hook)).
Can accept limitations if it helps to make code easier - e.g. max 64k buffer per frame?

**Comment by 2012yaya2007** [comment]
map --mem /dh.ima (fd0)
map --hook

splashimage --fill-color=0x3300
splashimage --offset=580=450=0x80 (fd0)/BritneyLZMA/easy2boot.bmp
splashimage --animated=0x83=1=26=130=150=(fd0)/BritneyLZMA/frame-01.bmp
splashimage (fd0)/BritneyLZMA/lt.jpg
splashimage --animated=0x90=10=2=730=520=(fd0)/BritneyLZMA/dh-hei-01.bmp

title animated1
splashimage --animated=0x83=5=3=230=150=(fd0)/BritneyLZMA/E2BRotate_frame_0001.bmp

title animated2
splashimage --animated=0x10=10=2=330=150=(fd0)/BritneyLZMA/dh-hei-01.bmp

title animated_stop
splashimage --animated=00

**Comment by steve6375** [comment]
Good idea :+1: 
I can use fd3 which should cause less interference.
It is not as good as loading them into memory automatically, but it is a good compromise.

```
map --mem --readonly /dh.ima (fd3)
map --hook
```

**Comment by steve6375** [comment]
grub4dos help text is inconsistent???
splashimage --offset[x]=[y] FILE   **<< has space before FILE**
splashimage --animated=[type]=[delay]=[last_num]=[x]=[y]=[name]  **<< has = before [name]**
also
[name] should be START_FILE?
and also maybe
splashimage [--offset[x]=[y]] FILE   **<< --offset is optional**

Other than that, new version seems to be working well :+1:

**Comment by 2012yaya2007** [comment]
agree

"loading them into memory automatically"
Do not want to use the G4D reserved memory.
The use of user memory,  prone to conflict.

**Comment by steve6375** [comment]
OK. I am very pleased with final solution! Thank you for all your work on this new feature :+1:

**Comment by steve6375** [comment]
Just found a problem!

password fred
hotkey -A
(load bitmap)
(load splashimage --animated)

When infinite animation is playing on menu and you have a password set, when you press SHIFT+P to enter the password, when you press a key the prompt moves to the top of the screen.
![image](https://cloud.githubusercontent.com/assets/1469350/13286865/e37eb5a2-dafb-11e5-8f86-45041ec4ebde.png)

Also, edit menu is on background!  SHIFT+e
![image](https://cloud.githubusercontent.com/assets/1469350/13286930/28e66b4e-dafc-11e5-9d49-8b4a0e98ff4c.png)

**Comment by steve6375** [comment]
Another bug
splashimage --animated (infinite)
splashimage --offset=33=44=/sprite.bmp  **<<< stops animation**

**Comment by steve6375** [comment]
2016-02-26 latest build broken!
animation no longer works
If enter password then screen goes to non-graphics mode
![image](https://cloud.githubusercontent.com/assets/1469350/13355387/00d48c06-dc98-11e5-9158-3b8e2581e313.png)
![image](https://cloud.githubusercontent.com/assets/1469350/13355394/0f2e930a-dc98-11e5-8f5b-c7ba121c418e.png)

**Comment by steve6375** [comment]
Sorry - ignore this! I did not realise the syntax has changed!
type now use for --offset :-)

**Comment by steve6375** [comment]
With this animated sequence - first frame 01 is displayed in different position to other frames.
if start from 02 then it is OK until 01 is then displayed, so something odd about 01.bmp?
Why?
```
set P=/_ISO/docs/ANIMATED_BMPS/DNA/xDNA_frame_0001.bmp
set trans=0x80 && set infinite=0x10  
set /A type=%infinite% + %trans%
set delay=0x3 ;; set end=3 ;; set offx=560 ;; set offy=140
splashimage --animated=%type%=%delay%=%end%=%offx%=%offy% %P% > nul
```

![image](https://cloud.githubusercontent.com/assets/1469350/13372352/9478be42-dd37-11e5-95f6-b0cc031b39ae.png)



[DNA.zip](https://github.com/chenall/grub4dos/files/149292/DNA.zip)

**Comment by steve6375** [comment]
Also, if play all 64 compressed bitmaps, some residue is left on screen.
![image](https://cloud.githubusercontent.com/assets/1469350/13372371/c12830b6-dd38-11e5-8808-5e5420f437aa.png)
[DNA_64.zip](https://github.com/chenall/grub4dos/files/149297/DNA_64.zip)

**Comment by steve6375** [comment]
2016-02-26
bug - if using --animated, first picture is not displayed until after delay
set ANIMATE=0x10=90=**60**=315=25  /_ISO/docs/Animated_BMPS/TIMER/1mingreen_frame_0001.bmp

first picture only appears **after** 3 seconds

**Comment by 2012yaya2007** [comment]
Has been corrected
http://bbs.wuyou.net/forum.php?mod=viewthread&tid=369720&page=1&extra=#pid3108602

**Comment by steve6375** [comment]
Still not fixed.
If I set delay of 72 then I get
1. background for 4 seconds
2. animated play for 4 seconds
3. end
to display background+single picture for 4 seconds from command line.
splashimage --animated=1=72=1=0=0 /bigpic01.bmp

also grub4dos reports Error 13 invalid executable??

**Comment by steve6375** [comment]
Also problem with infinite animation in new version - problem if set **99** as last frame
1. plays frames until last frame - e.g.  99 frames at 1/18 second = approx 7 seconds
**2. animation stops for approx 40 seconds**
3. goto 1

was Ok on 2016-02-26 version.

**Comment by steve6375** [comment]
minor bug
If splashimage --animated is used with a bad file specification followed by splashimage /background.bmp, 

```
graphicsmode -1 800
splashimage --animated=tt=dd=cc=xx=yy /bad/file.bmp
splashimage /background.bmp
```

then the **cursor state** seems to be changed. e.g. when you get to the menu, it displays the background splashimage OK, but when you hit SHIFT+P for password, you get a black line. Then press Enter and splashimage background disappears.
It only happens if bad file spec, but it would be better if it was fixed.

**Comment by 2012yaya2007** [comment]
i 'm sorry Upload error. Please download again.

"minor bug"
No see

**Comment by steve6375** [comment]
2016-02-29 - play 1 now works without delay - fixed thanks, but
bug: edit display not in console mode

```
graphicsmode -1 800
splashimage /_ISO/e2b/grub/background.bmp.gz

title reboot
reboot
```

in menu press e for edit
![image](https://cloud.githubusercontent.com/assets/1469350/13389701/e26e72f0-dec1-11e5-9ec6-cac49a63d5a8.png)

**Comment by steve6375** [comment]
P.S. Some animations are over 100 frames. Is it possible to use 001.bmp - 999.bmp ?
maybe
if 7th last character is 0 and 6th&5th last = 99 then increment 7th last to 1, so valid range is 01.bmp-99.bmp and 001.bmp-199.bmp? So compatible with previous version?

```
iftitle [if exist /DNA.ima] DNA animation \n Add DNA to the menu!
map --mem --read-only /DNA.ima (fd3)
map --hook
set P=(fd3)/DNA_orbit_animated_frame_0001.bmp
set trans=0x80 && set infinite=0x10  
set /A type=%infinite% + %trans%
set delay=0x3 ;; set end=120 ;; set offx=550 ;; set offy=0
splashimage --animated=%type%=%delay%=%end%=%offx%=%offy% %P% > nul
set trans= && set once= && set cycle= && set delay= && set type= && set end= && set offy= && set offx= && set P=
errorcheck off
boot
```

[DNA.zip](https://github.com/chenall/grub4dos/files/150634/DNA.zip)

**Comment by steve6375** [comment]
Bad filespec bug: - menu disappears

```
graphicsmode -1 800
splashimage /_ISO/e2b/grub/background.bmp.gz

title Bad Demo
errorcheck off
# file does not exist - so fails (but still delays)
splashimage --animated=1=36=1=550=0 /_ISO/docs/no_exist.bmp
# play animated infinite sequence
splashimage --animated=0x10=3=10=550=0 /_ISO/docs/animated_BMPS/TIMER/giphycat_frame_0001.bmp
boot

```

![image](https://cloud.githubusercontent.com/assets/1469350/13390363/c24de77c-dec5-11e5-8795-e92c5e143458.png)

**Comment by 2012yaya2007** [comment]
"bug: edit display not in console mode"
Press "E", can only be performed "d", "O", "o"
Once again the "E" button,Can edit.

"Bad filespec bug: - menu disappears"
delete "boot"

"001.bmp-199.bmp"
Is it necessary?

**Comment by steve6375** [comment]
I use boot because it makes the menu selectable for user.
What is best to use in a menu to make grub4dos return back to menu but be able to select item in menu? Menu must have boot or some other command or it is not selectable by user. e.g. 
configfile /no_exist.cfg

re. 199.bmp - yes, I have found several animations that are over 100 frames. Ideally I would like 999 max. please :-)

**Comment by 2012yaya2007** [comment]
Try the 3 digit animation

**Comment by steve6375** [comment]
Looks good! Help needs updating. What is maximum now 199 or 999?

**Comment by 2012yaya2007** [comment]
999

**Comment by steve6375** [comment]
I tried  SOLAR_SYSTEM_ANIMATION_frame_991.bmp to SOLAR_SYSTEM_ANIMATION_frame_993.bmp  but it only shows the first frame.

splashimage --animated=1=18=993=0=0 /SOLAR_SYSTEM_ANIMATION_frame_991.bmp

Is this expected?

**Comment by 2012yaya2007** [comment]
can only 001 - 999
cannot 991 - 993
The first frame must be 001

**Comment by steve6375** [comment]
OK, but for single frame can be  'frame.bmp' if I use  last=1 cycle=1 and then will display for 'delay' seconds as 'boilerplate' function.
splashimage --animated=1=18=1=200=200 /frame.bmp > nul
works OK for displaying 1 frame for 1 second. :+1:

**Comment by steve6375** [comment]
so valid names for a sequence are  frame01.bmp and frame001.bmp?

**Comment by 2012yaya2007** [comment]
/frame001.bmp

**Comment by 2012yaya2007** [comment]
yes

**Comment by 2012yaya2007** [comment]
May be frame.bmp or frame1.bmp or frame01.bmp or frame001.bmp
Not difficult, but the long code

**Comment by steve6375** [comment]
frame01.bmp and frame001.bmp is OK.
frame.bmp also works if just one picture wanted.
I think is OK now. I have not tested >199 animation though.

**Comment by 2012yaya2007** [comment]
"naming rules for name: xxxxxnn.xxx or xxxxxnnn.xxx.\n"
  "                       from 01 or 001, to xxxxx'last_num'.xxx\n"

**Comment by steve6375** [comment]
:+1:

**Comment by steve6375** [comment]
Aside: Do you know best way to exit/abort a menu and return back to same menu with same menu entry highlighted as before?

```
title sss
(etc)
if 1==1   **(exit and return to same menu)**
(etc)
boot

```

What command can be used for (exit and return to same menu) ???
I don't want to use configfile because I don't know the name of the menu I am running. Also I want the same menu entry highlighted as before. If I use configfile then it will return to default menu.
Is there a 'exit' or 'exitmenu' or 'return' command?

**Comment by 2012yaya2007** [comment]
There seems to be no better way.

"because I don't know the name of the menu I am running"
calc *0x307FFC-0x110000 > nul && configfile (md)4+8 ! configfile (md)0x880+0x200
or
write 0x307ff8 1 && configfile
I don't know if I can

"Also I want the same menu entry highlighted as before"
Modify the default item in the menu only.

**Comment by steve6375** [comment]
Closing as animation works great - thanks!
